# Generated by Django 6.0 on 2025-12-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='preferences',
            new_name='name',
        ),
    ]
