# Generated by Django 6.0 on 2025-12-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preferences',
            name='sources',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_preferences',
            name='topics',
            field=models.CharField(max_length=20),
        ),
    ]
