# Generated by Django 6.0 on 2025-12-12 06:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_user_preferences_sources_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_preferences',
            new_name='UserPreferences',
        ),
        migrations.AlterUniqueTogether(
            name='userpreferences',
            unique_together={('user', 'category', 'topics', 'sources')},
        ),
    ]
