# Generated by Django 6.0 on 2025-12-15 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_user_preferences_userpreferences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpreferences',
            unique_together={('user', 'category', 'topics')},
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='sources',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
