# Generated by Django 6.0 on 2025-12-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_userpreferences_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencecategory',
            name='user',
        ),
    ]
